name = "lisatmiller-ai"
compatibility_date = "2026-07-18"

[assets]
directory = "./public_html"

routes = [
  { pattern = "lisatmiller.ai/*", zone_name = "lisatmiller.ai" },
  { pattern = "www.lisatmiller.ai/*", zone_name = "lisatmiller.ai" }
]
